# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_infer_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_infer_service.proto\x12\x12grpc_infer_service\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2b\n\x10InferenceService\x12N\n\x0fGetImgClsResult\x12\x1b.grpc_infer_service.Request\x1a\x1c.grpc_infer_service.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_infer_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=48
  _globals['_REQUEST']._serialized_end=71
  _globals['_RESPONSE']._serialized_start=73
  _globals['_RESPONSE']._serialized_end=100
  _globals['_INFERENCESERVICE']._serialized_start=102
  _globals['_INFERENCESERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
