// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc_infer_service.proto

#include "grpc_infer_service.pb.h"
#include "grpc_infer_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grpc_infer_service {

static const char* InferenceService_method_names[] = {
  "/grpc_infer_service.InferenceService/GetImgClsResult",
};

std::unique_ptr< InferenceService::Stub> InferenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceService::Stub> stub(new InferenceService::Stub(channel, options));
  return stub;
}

InferenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetImgClsResult_(InferenceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InferenceService::Stub::GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc_infer_service::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_infer_service::Request, ::grpc_infer_service::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetImgClsResult_, context, request, response);
}

void InferenceService::Stub::async::GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_infer_service::Request, ::grpc_infer_service::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetImgClsResult_, context, request, response, std::move(f));
}

void InferenceService::Stub::async::GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetImgClsResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>* InferenceService::Stub::PrepareAsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_infer_service::Response, ::grpc_infer_service::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetImgClsResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>* InferenceService::Stub::AsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetImgClsResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

InferenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceService::Service, ::grpc_infer_service::Request, ::grpc_infer_service::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_infer_service::Request* req,
             ::grpc_infer_service::Response* resp) {
               return service->GetImgClsResult(ctx, req, resp);
             }, this)));
}

InferenceService::Service::~Service() {
}

::grpc::Status InferenceService::Service::GetImgClsResult(::grpc::ServerContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_infer_service

