// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc_infer_service.proto
#ifndef GRPC_grpc_5finfer_5fservice_2eproto__INCLUDED
#define GRPC_grpc_5finfer_5fservice_2eproto__INCLUDED

#include "grpc_infer_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grpc_infer_service {

// The greeting service definition.
class InferenceService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_infer_service.InferenceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc_infer_service::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>> AsyncGetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>>(AsyncGetImgClsResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>> PrepareAsyncGetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>>(PrepareAsyncGetImgClsResultRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>* AsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_infer_service::Response>* PrepareAsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc_infer_service::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>> AsyncGetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>>(AsyncGetImgClsResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>> PrepareAsyncGetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>>(PrepareAsyncGetImgClsResultRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, std::function<void(::grpc::Status)>) override;
      void GetImgClsResult(::grpc::ClientContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>* AsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_infer_service::Response>* PrepareAsyncGetImgClsResultRaw(::grpc::ClientContext* context, const ::grpc_infer_service::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetImgClsResult_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetImgClsResult(::grpc::ServerContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImgClsResult(::grpc::ServerContext* context, ::grpc_infer_service::Request* request, ::grpc::ServerAsyncResponseWriter< ::grpc_infer_service::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetImgClsResult<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_infer_service::Request, ::grpc_infer_service::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc_infer_service::Request* request, ::grpc_infer_service::Response* response) { return this->GetImgClsResult(context, request, response); }));}
    void SetMessageAllocatorFor_GetImgClsResult(
        ::grpc::MessageAllocator< ::grpc_infer_service::Request, ::grpc_infer_service::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_infer_service::Request, ::grpc_infer_service::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImgClsResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetImgClsResult<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImgClsResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetImgClsResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImgClsResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetImgClsResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetImgClsResult() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_infer_service::Request, ::grpc_infer_service::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_infer_service::Request, ::grpc_infer_service::Response>* streamer) {
                       return this->StreamedGetImgClsResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetImgClsResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetImgClsResult(::grpc::ServerContext* /*context*/, const ::grpc_infer_service::Request* /*request*/, ::grpc_infer_service::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetImgClsResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_infer_service::Request,::grpc_infer_service::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetImgClsResult<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetImgClsResult<Service > StreamedService;
};

}  // namespace grpc_infer_service


#endif  // GRPC_grpc_5finfer_5fservice_2eproto__INCLUDED
