# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_infer_service_pb2 as grpc__infer__service__pb2


class InferenceServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImgClsResult = channel.unary_unary(
                '/grpc_infer_service.InferenceService/GetImgClsResult',
                request_serializer=grpc__infer__service__pb2.Request.SerializeToString,
                response_deserializer=grpc__infer__service__pb2.Response.FromString,
                )


class InferenceServiceServicer(object):
    """The greeting service definition.
    """

    def GetImgClsResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImgClsResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImgClsResult,
                    request_deserializer=grpc__infer__service__pb2.Request.FromString,
                    response_serializer=grpc__infer__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_infer_service.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetImgClsResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_infer_service.InferenceService/GetImgClsResult',
            grpc__infer__service__pb2.Request.SerializeToString,
            grpc__infer__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
